# Introduction {#intro}

### 기계보조 내용분석

기계를 이용한 분석의 장점은 대용량의 데이터 처리이나 분석의 정밀성이 떨어진다는 단점이 있다. 정밀한 분석은 사람이 직접 수행해야 하지만 대용량의 데이터를 처리할 수 없는 한계가 있다. 

두 방법을 혼용해 기계를 이용해 대용량의 데이터에서 기본적인 분석을 수행하고, 이를 토대로 사람이 추가적으로 분석을 수행한다면 대용량의 데이터를 보다 정밀하게 분석할 수 있다. 


### 지도학습, 비지도학습, 반지도학습

기계를 이용한 텍스트분석은 크게 지도학습과 비지도학습을 이용한 분류로 구분된다. 지도학습을 이용한 분류를 위해서는 대용량의 학습데이터가 필요하다. 감정어 사전을 구성해 텍스트의 감정을 분류하는 감정분석이 전형적인 지도학습이다. 감정사전의 단어의 갯수를 계산하는 단순한 방법부터 신경망 알고리듬을 이용하는 방법 등 다양한 접근이 있다.  `caret`패키지에서 다양한 지도학습 알고리듬을 제공한다.

비지도학습은 학습데이터 없이 기계가 확률분포를 이용해 유사한 것끼리 군집한다. LDA를 이용한 텍스트군집, 주제모형분석(topic modeling)이 전형적인 비지도학습이다. `topicmodels` `mallet` `stm` `ctm` `btm` 등의 패키지를 이용할 수 있다.  

지도학습과 비지도학습의 장점을 취한 접근이 반지도학습이다. 대용량의 학습데이터를 마련하기 보다 소규모의 씨앗 역할을 하는 단어에 기반해 기계가 군집하는 방식이다. 씨앗역할 하는 단어의 설정을 하기 위해서는 논리가 필요하므로 이론기반 토픽모델링이라 할 수 있다. `seededlda` `keyATM` 등의 패키지가 있다. (참고: `keyATM`은 개발자가 iOS 환경에서 작업하면서 윈도에서의 인코딩을 고려하지 않았기 때문에 한글윈도에서는 분석결과가  유니코드로 산출된다.)

### 절차

1. 주제어확인
분석 말뭉치에 대해 비지도 토픽모델링으로 문서에 분포된 주제와 주제어를 확인한다. 

2. 씨앗주제어 설정
분석목표를 달성하는데 필요한 씨앗으로 활용할 주제어를 설정한다. 

3. 씨앗주제어사전 구성
비지도 토픽모델링으로 확보한 주제어와 분석목표에 따른 씨앗주제어를 활용해 씨앗주제어 사전을 구성한다. 

4. 반지도 토픽모델링 시행

.

