# 방법론 {#method}

### 품질 측정의 자동화와 한계 {-}

전통적으로 언론보도에 대한 품질측정은 인간의 수작업에 의해 이뤄졌다. 사람은 복잡한 알고리듬을 적용할 수 있어 내용 분석의 정밀성이 높기 때문이다. 단점은 일관성이 떨어지고 다룰 수 있는 데이터의 적다는 데 있다. 반면 기계는 일관성이 높고 많은 양의 데이터를 다룰 수 있는 장점이 있지만 단순한 알고리듬을 적용해 정밀성이 떨어진다는 단점이 있다. 

이런 이유로 뉴스 품질을 측정하다는 알고리듬(예: 네이버 뉴스 추천 알고리듬)이 실제로 적용하는 기준은 품질이 아니라 사용자의 선호도다. 네이버가 공개한 자동화 방식의 뉴스품질 측정에 따르면 각 뉴스 기사의 제목, 본문 등 콘텐츠 정보와 네이버 뉴스르 이용하는 사용자들의 클릭수와 체류시간을 고려한다 (네이버검색, 2021.7.21). 사용자의 관점에서 만족스럽게 읽은 기사를 고품질의 기사로 판단한다는 것인데, 여기서 만족의 지표는 클릭스와 체류시간이다. 클릭수가 높은데 체류시간이 짧으면 만족도가 떨어진다고 판단한 것이다. 클릭 후 이탈없이 적정시간 동안 체류하며 읽은 기사를 만족도가 높은 기사로서 고품질이라고 분류했다. 그러나, 네이버가 측정지표로 활용한 클릭수와 체류시간은 관심성의 지표로 활용할 수 있지만, 정확성와 구체성의 지표에는 해당하지 않는다.  

보다 체계적인 접근은 보도품질에 대한 계량적인 평가요인을 추출하려는 시도다. 오세욱과  송해엽(2020)은 뉴스 트러스트 위원회 활동을 통해 기자명, 기사의 길이, 인용문 수, 제목의 길이, 제목의 물음표 및 느낌표 수, 수치 인용 수, 이미지의 수, 평균 문장의 길이, 제목의 부사 수, 문장 당 평균 부사 수, 기사 본문 중 인용문 비중 등 11개 평가기준을 알고리듬의 요인으로 제시했다. 뉴스 트러스트 위원회의 11개 지표 역시 뉴스의 길이를 제외하면 정확성, 구체성, 및 관심성을 반영하는 지표라 할 수 없다. 




## 품질측정1: 이론기반 토픽모델링 

##### 안도현 {-}



### 기계보조 내용분석

기계 이용 분석 장점(대용량 처리) + 인간 분석(정밀성)
기계를 이용해 대용량의 데이터에서 기본적인 분석을 수행하고, 이를 토대로 사람이 추가적으로 분석 수행
기계를 이용해 대용량의 자료에서 분석 대상 선별해 사람이 내용분석

지도학습, 비지도학습, 반지도학습
지도학습: 기 분류한 학습데이터로 기계를 훈련시켜 분류
감정분석
비지도학습:  학습데이터 없이 기계가 확률분포를 이용해 유사한 것끼리 군집
토픽모델링 LDA
반지도학습: 소규모의 씨앗 역할을 하는 단어에 기반해 기계가 군집하는 방식이다. 
이론기반 토픽모델링 seededLDA



### 기계보조 내용분석

기계를 이용한 분석의 장점은 대용량의 데이터 처리이나 분석의 정밀성이 떨어진다는 단점이 있다. 정밀한 분석은 사람이 직접 수행해야 하지만 대용량의 데이터를 처리할 수 없는 한계가 있다. 

두 방법을 혼용해 기계를 이용해 대용량의 데이터에서 기본적인 분석을 수행하고, 이를 토대로 사람이 추가적으로 분석을 수행한다면 대용량의 데이터를 보다 정밀하게 분석할 수 있다. 


### 지도학습, 비지도학습, 반지도학습

기계를 이용한 텍스트분석은 크게 지도학습과 비지도학습을 이용한 분류로 구분된다. 지도학습을 이용한 분류를 위해서는 대용량의 학습데이터가 필요하다. 감정어 사전을 구성해 텍스트의 감정을 분류하는 감정분석이 전형적인 지도학습이다. 감정사전의 단어의 갯수를 계산하는 단순한 방법부터 신경망 알고리듬을 이용하는 방법 등 다양한 접근이 있다.  `caret`패키지에서 다양한 지도학습 알고리듬을 제공한다.

비지도학습은 학습데이터 없이 기계가 확률분포를 이용해 유사한 것끼리 군집한다. LDA를 이용한 텍스트군집, 주제모형분석(topic modeling)이 전형적인 비지도학습이다. `topicmodels` `mallet` `stm` `ctm` `btm` 등의 패키지를 이용할 수 있다.  

지도학습과 비지도학습의 장점을 취한 접근이 반지도학습이다. 대용량의 학습데이터를 마련하기 보다 소규모의 씨앗 역할을 하는 단어에 기반해 기계가 군집하는 방식이다. 씨앗역할 하는 단어의 설정을 하기 위해서는 논리가 필요하므로 이론기반 토픽모델링이라 할 수 있다. `seededlda` `keyATM` 등의 패키지가 있다. (참고: `keyATM`은 개발자가 iOS 환경에서 작업하면서 윈도에서의 인코딩을 고려하지 않았기 때문에 한글윈도에서는 분석결과가  유니코드로 산출된다.)

### 절차

1. 주제어확인
분석 말뭉치에 대해 비지도 토픽모델링으로 문서에 분포된 주제와 주제어를 확인한다. 

2. 씨앗주제어 설정
분석목표를 달성하는데 필요한 씨앗으로 활용할 주제어를 설정한다. 

3. 씨앗주제어사전 구성
비지도 토픽모델링으로 확보한 주제어와 분석목표에 따른 씨앗주제어를 활용해 씨앗주제어 사전을 구성한다. 

4. 반지도 토픽모델링 시행




## 품질측정2: 자연어 생성

### 자연어 생성을 통한 감염병 보도 기사 품질 측정의 여정 {-}

##### 윤호영 {-}

### 목차 {-}

**I. 자연어 생성과 품질 측정 : 두 가지 상이한 접근법**  
  I.1. 지도학습 기반 자연어 생성 방식의 품질 평가  
  I.2. 데이터기반 자연어 생성 방식의 품질 거리 측정 모델


**II. 자연어 생성의 두 가지 접근법**  
  II.1. 단어기반 접근법 (Bottom-Up Approach)  
  II.2. 문장기반 접근법 (Holistic Approach)


**III. 문장 유사도 측정**  
  III.1. 레벤슈타인(Levenshtein Distance) 문장 유사도 측정  
  III-2. 몇 가지 가장 유명한 다른 방법들


**IV. 뉴스 품질과 자연어 생성 관련 문헌(Updating)**  


**V. 자연어 생성 예제**  
  V-1. Bi-gram 기반 자연어 예제  
  V-2. LSTM 기반 자연어 문장 생성


**VI. 토론**

### 본문과 코드 {-}
윤호영 교수의 "자연어 생성을 통한 감염병 보도 기사 품질 측정의 여정"에 대한 본문과 코드는 별도의 문서로 작성했다. [외부 링크](https://colab.research.google.com/drive/1MVX2e1AzEH8pFxvMUunY_pG2LxQYiW-Y?usp=sharing#scrollTo=hhs0oJ0A3GAU)


